#!/usr/bin/env bash
# =============================================================================
# apply-secrets.sh — Generate lab secrets and cert-manager resources
# =============================================================================
# Usage:
#   ./deploy/apply-secrets.sh [namespace] [--dry-run]
#   # example: ./deploy/apply-secrets.sh owl --dry-run
#
# This script:
#   1. Generates random passwords for all services
#   2. Creates the target namespace
#   3. Writes values.lab-secrets.yaml with all secrets filled in
#   4. Prints the helm install command
#
# The generated values.lab-secrets.yaml is gitignored and should NEVER be
# committed. Re-run this script to regenerate.
# =============================================================================

set -euo pipefail

NAMESPACE="${1:-owl}"
DRY_RUN="${2:-}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
SECRETS_FILE="$REPO_DIR/values.lab-secrets.yaml"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
rand_password() { openssl rand -base64 32 | tr -d '/+=' | head -c 32; }
rand_hex() { openssl rand -hex "$1"; }

# ---------------------------------------------------------------------------
# GHCR credentials — needed to pull private images and Helm charts
# ---------------------------------------------------------------------------
echo ""
read -rp "GitHub username for GHCR: " GHCR_USERNAME
read -rsp "GitHub PAT (read:packages scope): " GHCR_PAT
echo ""

echo "==> Generating random passwords..."

# Database passwords (used in both init script and connection URLs)
PG_SUPERUSER_PW=$(rand_password)
NIGHTOWL_DB_PW=$(rand_password)
KEYCLOAK_DB_PW=$(rand_password)
ZAMMAD_DB_PW=$(rand_password)
KEEP_DB_PW=$(rand_password)
OUTLINE_DB_PW=$(rand_password)

# Application secrets
OWLSTACK_SESSION_SECRET=$(rand_hex 32)
OWLSTACK_OIDC_SECRET=$(rand_password)
OWLSTACK_ENCRYPTION_KEY=$(rand_hex 32)

# Redis
REDIS_PW=$(rand_password)

# Keycloak admin
KEYCLOAK_ADMIN_PW=$(rand_password)

# Zammad token for Owlstack integration
ZAMMAD_OWLSTACK_TOKEN=$(rand_hex 32)

# Outline API token for Owlstack integration
OUTLINE_API_TOKEN=$(rand_hex 32)

# Webhook/API keys
OWLSTACK_WEBHOOK_KEY="ow_$(rand_hex 32)"
KEEP_API_KEY=$(rand_hex 20)
KEEP_ADMIN_API_KEY=$(rand_hex 20)

# Keep secrets
KEEP_NEXTAUTH_SECRET=$(rand_hex 32)
KEEP_OIDC_SECRET=$(rand_password)
KEEP_OAUTH2_PROXY_COOKIE_SECRET=$(rand_hex 16)

# Outline secrets
OUTLINE_SECRET_KEY=$(rand_hex 32)
OUTLINE_UTILS_SECRET=$(rand_hex 32)
OUTLINE_OIDC_SECRET=$(rand_password)

# ---------------------------------------------------------------------------
# Step 1: Create namespace (if not exists)
# ---------------------------------------------------------------------------
echo "==> Ensuring namespace '$NAMESPACE'..."
if [ "$DRY_RUN" != "--dry-run" ]; then
  kubectl create namespace "$NAMESPACE" --dry-run=client -o yaml | kubectl apply -f -
else
  echo "    [DRY RUN] Would create namespace '$NAMESPACE'"
fi

# ---------------------------------------------------------------------------
# Step 2: Write values.lab-secrets.yaml
# ---------------------------------------------------------------------------
echo "==> Writing $SECRETS_FILE..."

cat > "$SECRETS_FILE" <<SECRETS_EOF
# =============================================================================
# values.lab-secrets.yaml — GENERATED BY deploy/apply-secrets.sh
# =============================================================================
# DO NOT COMMIT THIS FILE. It contains real passwords.
# Regenerate with: ./deploy/apply-secrets.sh
# =============================================================================

# -----------------------------------------------------------------------------
# GHCR registry credentials
# -----------------------------------------------------------------------------
registryCredentials:
  username: "${GHCR_USERNAME}"
  password: "${GHCR_PAT}"

# -----------------------------------------------------------------------------
# Owlstack secrets
# -----------------------------------------------------------------------------
owlstack:
  secrets:
    databaseUrl: "postgres://nightowl:${NIGHTOWL_DB_PW}@owl-postgresql:5432/nightowl?sslmode=disable"
    redisUrl: "redis://:${REDIS_PW}@owl-redis-master:6379/0"
    oidcClientSecret: "${OWLSTACK_OIDC_SECRET}"
    sessionSecret: "${OWLSTACK_SESSION_SECRET}"
    encryptionKey: "${OWLSTACK_ENCRYPTION_KEY}"
    zammadToken: "${ZAMMAD_OWLSTACK_TOKEN}"
    outlineApiToken: "${OUTLINE_API_TOKEN}"
    webhookKey: "${OWLSTACK_WEBHOOK_KEY}"
    keepApiKey: "${KEEP_ADMIN_API_KEY}"

# -----------------------------------------------------------------------------
# PostgreSQL
# -----------------------------------------------------------------------------
postgresql:
  auth:
    postgresPassword: "${PG_SUPERUSER_PW}"
  primary:
    initdb:
      scripts:
        create-databases.sql: |
          -- Create databases
          CREATE DATABASE keycloak;
          CREATE DATABASE zammad;
          CREATE DATABASE keep;
          CREATE DATABASE outline;

          -- Create users with generated passwords
          CREATE USER nightowl WITH PASSWORD '${NIGHTOWL_DB_PW}';
          CREATE USER keycloak WITH PASSWORD '${KEYCLOAK_DB_PW}';
          CREATE USER zammad WITH PASSWORD '${ZAMMAD_DB_PW}';
          CREATE USER keep WITH PASSWORD '${KEEP_DB_PW}';
          CREATE USER outline WITH PASSWORD '${OUTLINE_DB_PW}';

          -- Grant privileges
          GRANT ALL PRIVILEGES ON DATABASE nightowl TO nightowl;
          GRANT ALL PRIVILEGES ON DATABASE keycloak TO keycloak;
          GRANT ALL PRIVILEGES ON DATABASE zammad TO zammad;
          GRANT ALL PRIVILEGES ON DATABASE keep TO keep;
          GRANT ALL PRIVILEGES ON DATABASE outline TO outline;

          -- Grant schema permissions (required for PG 15+)
          \\connect nightowl
          GRANT ALL ON SCHEMA public TO nightowl;
          \\connect keycloak
          GRANT ALL ON SCHEMA public TO keycloak;
          \\connect zammad
          GRANT ALL ON SCHEMA public TO zammad;
          \\connect keep
          GRANT ALL ON SCHEMA public TO keep;
          \\connect outline
          GRANT ALL ON SCHEMA public TO outline;

# -----------------------------------------------------------------------------
# Redis
# -----------------------------------------------------------------------------
redis:
  auth:
    password: "${REDIS_PW}"

# -----------------------------------------------------------------------------
# Keycloak
# -----------------------------------------------------------------------------
keycloak:
  auth:
    adminPassword: "${KEYCLOAK_ADMIN_PW}"
  externalDatabase:
    password: "${KEYCLOAK_DB_PW}"

# -----------------------------------------------------------------------------
# Zammad
# -----------------------------------------------------------------------------
zammad:
  owlstackToken: "${ZAMMAD_OWLSTACK_TOKEN}"
  zammadConfig:
    postgresql:
      pass: "${ZAMMAD_DB_PW}"
    redis:
      pass: "${REDIS_PW}"

# -----------------------------------------------------------------------------
# Keep
# -----------------------------------------------------------------------------
keep:
  oidcClientSecret: "${KEEP_OIDC_SECRET}"
  secrets:
    databaseConnectionString: "postgresql+psycopg2://keep:${KEEP_DB_PW}@owl-postgresql:5432/keep"
    nextauthSecret: "${KEEP_NEXTAUTH_SECRET}"
    keepApiKey: "${KEEP_API_KEY}"
    keepAdminApiKey: "${KEEP_ADMIN_API_KEY}"
  oauth2Proxy:
    cookieSecret: "${KEEP_OAUTH2_PROXY_COOKIE_SECRET}"

# -----------------------------------------------------------------------------
# Outline
# -----------------------------------------------------------------------------
outline:
  oidcClientSecret: "${OUTLINE_OIDC_SECRET}"
  secrets:
    secretKey: "${OUTLINE_SECRET_KEY}"
    utilsSecret: "${OUTLINE_UTILS_SECRET}"
    databaseUrl: "postgres://outline:${OUTLINE_DB_PW}@owl-postgresql:5432/outline?sslmode=disable"
    redisUrl: "redis://:${REDIS_PW}@owl-redis-master:6379/3"
    oidcClientSecret: "${OUTLINE_OIDC_SECRET}"
    # Fill these after creating a Garage key (see NOTES/docs):
    awsAccessKeyId: ""
    awsSecretAccessKey: ""
SECRETS_EOF

echo "    Written to $SECRETS_FILE"

# ---------------------------------------------------------------------------
# Step 3: Save credentials to a reference file
# ---------------------------------------------------------------------------
CREDS_FILE="$REPO_DIR/deploy/.lab-credentials"
cat > "$CREDS_FILE" <<CREDS_EOF
# Lab credentials — generated $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Keep this file safe. Do NOT commit.

# GHCR registry
GHCR_USERNAME=${GHCR_USERNAME}
GHCR_PAT=${GHCR_PAT}

# PostgreSQL superuser
PG_SUPERUSER_PASSWORD=${PG_SUPERUSER_PW}

# Database user passwords
NIGHTOWL_DB_PASSWORD=${NIGHTOWL_DB_PW}
KEYCLOAK_DB_PASSWORD=${KEYCLOAK_DB_PW}
ZAMMAD_DB_PASSWORD=${ZAMMAD_DB_PW}

# Application secrets
OWLSTACK_SESSION_SECRET=${OWLSTACK_SESSION_SECRET}
OWLSTACK_OIDC_CLIENT_SECRET=${OWLSTACK_OIDC_SECRET}
OWLSTACK_ENCRYPTION_KEY=${OWLSTACK_ENCRYPTION_KEY}
OWLSTACK_WEBHOOK_KEY=${OWLSTACK_WEBHOOK_KEY}

# Redis
REDIS_PASSWORD=${REDIS_PW}

# Keycloak admin
KEYCLOAK_ADMIN_USER=admin
KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PW}

# Zammad
ZAMMAD_OWLSTACK_TOKEN=${ZAMMAD_OWLSTACK_TOKEN}
ZAMMAD_DB_PASSWORD=${ZAMMAD_DB_PW}

# Outline API Token (Owlstack integration)
OUTLINE_API_TOKEN=${OUTLINE_API_TOKEN}

# Keep
KEEP_DB_PASSWORD=${KEEP_DB_PW}
KEEP_NEXTAUTH_SECRET=${KEEP_NEXTAUTH_SECRET}
KEEP_OIDC_CLIENT_SECRET=${KEEP_OIDC_SECRET}
KEEP_OAUTH2_PROXY_COOKIE_SECRET=${KEEP_OAUTH2_PROXY_COOKIE_SECRET}
KEEP_API_KEY=${KEEP_API_KEY}
KEEP_ADMIN_API_KEY=${KEEP_ADMIN_API_KEY}

# Outline
OUTLINE_DB_PASSWORD=${OUTLINE_DB_PW}
OUTLINE_SECRET_KEY=${OUTLINE_SECRET_KEY}
OUTLINE_UTILS_SECRET=${OUTLINE_UTILS_SECRET}
OUTLINE_OIDC_CLIENT_SECRET=${OUTLINE_OIDC_SECRET}
OUTLINE_AWS_ACCESS_KEY_ID=
OUTLINE_AWS_SECRET_ACCESS_KEY=

# URLs
NIGHTOWL_URL=https://nightowl.devops.lab
KEYCLOAK_URL=https://keycloak.devops.lab
ZAMMAD_URL=https://zammad.devops.lab
KEEP_URL=https://keep.devops.lab
OUTLINE_URL=https://outline.devops.lab
CREDS_EOF
chmod 600 "$CREDS_FILE"
echo "    Credentials saved to $CREDS_FILE"

# ---------------------------------------------------------------------------
# Step 4: Print the install command
# ---------------------------------------------------------------------------
echo ""
echo "============================================================================="
echo "  Lab secrets generated successfully!"
echo "============================================================================="
echo ""
echo "To deploy the Owl platform:"
echo ""
echo "  # 1. Build Helm dependencies"
echo "  cd $REPO_DIR"
echo "  helm dep build ."
echo ""
echo "  # 2. Install (or upgrade) the umbrella chart"
echo "  helm install owl . \\"
echo "    --namespace $NAMESPACE \\"
echo "    --create-namespace \\"
echo "    -f values.lab.yaml \\"
echo "    -f values.lab-secrets.yaml"
echo ""
echo "  # Or upgrade an existing release:"
echo "  helm upgrade owl . \\"
echo "    --namespace $NAMESPACE \\"
echo "    -f values.lab.yaml \\"
echo "    -f values.lab-secrets.yaml"
echo ""
echo "  # 3. Keycloak realm is imported automatically via post-install hook."
echo "  #    Check its status with:"
echo "  kubectl get jobs -n $NAMESPACE -l app.kubernetes.io/name=keycloak-realm-import"
echo ""
echo "Credentials file: $CREDS_FILE"
echo "============================================================================="
