#!/usr/bin/env bash
# =============================================================================
# apply-secrets.sh — Generate lab secrets and cert-manager resources
# =============================================================================
# Usage:
#   ./deploy/apply-secrets.sh [--namespace owl] [--dry-run]
#
# This script:
#   1. Generates random passwords for all services
#   2. Creates the target namespace
#   3. Writes values.lab-secrets.yaml with all secrets filled in
#   4. Prints the helm install command
#
# The generated values.lab-secrets.yaml is gitignored and should NEVER be
# committed. Re-run this script to regenerate.
# =============================================================================

set -euo pipefail

NAMESPACE="${1:-owl}"
DRY_RUN="${2:-}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
SECRETS_FILE="$REPO_DIR/values.lab-secrets.yaml"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
rand_password() { openssl rand -base64 32 | tr -d '/+=' | head -c 32; }
rand_hex() { openssl rand -hex "$1"; }

echo "==> Generating random passwords..."

# Database passwords (used in both init script and connection URLs)
PG_SUPERUSER_PW=$(rand_password)
NIGHTOWL_DB_PW=$(rand_password)
BOOKOWL_DB_PW=$(rand_password)
TICKETOWL_DB_PW=$(rand_password)
KEYCLOAK_DB_PW=$(rand_password)

# Application secrets
NIGHTOWL_SESSION_SECRET=$(rand_hex 32)
NIGHTOWL_OIDC_SECRET=$(rand_password)
BOOKOWL_SECRET_KEY=$(rand_hex 32)
BOOKOWL_NIGHTOWL_API_KEY="bw_$(rand_hex 20)"
TICKETOWL_ENCRYPTION_KEY=$(rand_hex 32)
TICKETOWL_NIGHTOWL_API_KEY="to_$(rand_hex 20)"
TICKETOWL_BOOKOWL_API_KEY="to_$(rand_hex 20)"

# Keycloak admin
KEYCLOAK_ADMIN_PW=$(rand_password)

# MinIO
MINIO_ROOT_USER="minioadmin"
MINIO_ROOT_PW=$(rand_password)

# ---------------------------------------------------------------------------
# Step 1: Create namespace (if not exists)
# ---------------------------------------------------------------------------
echo "==> Ensuring namespace '$NAMESPACE'..."
if [ "$DRY_RUN" != "--dry-run" ]; then
  kubectl create namespace "$NAMESPACE" --dry-run=client -o yaml | kubectl apply -f -
else
  echo "    [DRY RUN] Would create namespace '$NAMESPACE'"
fi

# ---------------------------------------------------------------------------
# Step 2: Write values.lab-secrets.yaml
# ---------------------------------------------------------------------------
echo "==> Writing $SECRETS_FILE..."

cat > "$SECRETS_FILE" <<SECRETS_EOF
# =============================================================================
# values.lab-secrets.yaml — GENERATED BY deploy/apply-secrets.sh
# =============================================================================
# DO NOT COMMIT THIS FILE. It contains real passwords.
# Regenerate with: ./deploy/apply-secrets.sh
# =============================================================================

# -----------------------------------------------------------------------------
# NightOwl secrets
# -----------------------------------------------------------------------------
nightowl:
  secrets:
    databaseUrl: "postgres://nightowl:${NIGHTOWL_DB_PW}@owl-postgresql:5432/nightowl?sslmode=disable"
    oidcClientSecret: "${NIGHTOWL_OIDC_SECRET}"
    sessionSecret: "${NIGHTOWL_SESSION_SECRET}"

# -----------------------------------------------------------------------------
# BookOwl secrets
# -----------------------------------------------------------------------------
bookowl:
  secretKey: "${BOOKOWL_SECRET_KEY}"
  database:
    url: "postgres://bookowl:${BOOKOWL_DB_PW}@owl-postgresql:5432/bookowl?sslmode=disable"
  nightowl:
    apiKey: "${BOOKOWL_NIGHTOWL_API_KEY}"

# -----------------------------------------------------------------------------
# TicketOwl secrets
# -----------------------------------------------------------------------------
ticketowl:
  secrets:
    dbUrl: "postgres://ticketowl:${TICKETOWL_DB_PW}@owl-postgresql:5432/ticketowl?sslmode=disable"
    encryptionKey: "${TICKETOWL_ENCRYPTION_KEY}"
    nightowlApiKey: "${TICKETOWL_NIGHTOWL_API_KEY}"
    bookowlApiKey: "${TICKETOWL_BOOKOWL_API_KEY}"

# -----------------------------------------------------------------------------
# PostgreSQL
# -----------------------------------------------------------------------------
postgresql:
  auth:
    postgresPassword: "${PG_SUPERUSER_PW}"
  primary:
    initdb:
      scripts:
        create-databases.sql: |
          -- Create databases
          CREATE DATABASE bookowl;
          CREATE DATABASE ticketowl;
          CREATE DATABASE keycloak;

          -- Create users with generated passwords
          CREATE USER nightowl WITH PASSWORD '${NIGHTOWL_DB_PW}';
          CREATE USER bookowl WITH PASSWORD '${BOOKOWL_DB_PW}';
          CREATE USER ticketowl WITH PASSWORD '${TICKETOWL_DB_PW}';
          CREATE USER keycloak WITH PASSWORD '${KEYCLOAK_DB_PW}';

          -- Grant privileges
          GRANT ALL PRIVILEGES ON DATABASE nightowl TO nightowl;
          GRANT ALL PRIVILEGES ON DATABASE bookowl TO bookowl;
          GRANT ALL PRIVILEGES ON DATABASE ticketowl TO ticketowl;
          GRANT ALL PRIVILEGES ON DATABASE keycloak TO keycloak;

          -- Grant schema permissions (required for PG 15+)
          \\connect nightowl
          GRANT ALL ON SCHEMA public TO nightowl;
          \\connect bookowl
          GRANT ALL ON SCHEMA public TO bookowl;
          \\connect ticketowl
          GRANT ALL ON SCHEMA public TO ticketowl;
          \\connect keycloak
          GRANT ALL ON SCHEMA public TO keycloak;

# -----------------------------------------------------------------------------
# Keycloak
# -----------------------------------------------------------------------------
keycloak:
  auth:
    adminPassword: "${KEYCLOAK_ADMIN_PW}"
  externalDatabase:
    password: "${KEYCLOAK_DB_PW}"

# -----------------------------------------------------------------------------
# MinIO
# -----------------------------------------------------------------------------
minio:
  auth:
    rootUser: "${MINIO_ROOT_USER}"
    rootPassword: "${MINIO_ROOT_PW}"
SECRETS_EOF

echo "    Written to $SECRETS_FILE"

# ---------------------------------------------------------------------------
# Step 3: Save credentials to a reference file
# ---------------------------------------------------------------------------
CREDS_FILE="$REPO_DIR/deploy/.lab-credentials"
cat > "$CREDS_FILE" <<CREDS_EOF
# Lab credentials — generated $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Keep this file safe. Do NOT commit.

# PostgreSQL superuser
PG_SUPERUSER_PASSWORD=${PG_SUPERUSER_PW}

# Database user passwords
NIGHTOWL_DB_PASSWORD=${NIGHTOWL_DB_PW}
BOOKOWL_DB_PASSWORD=${BOOKOWL_DB_PW}
TICKETOWL_DB_PASSWORD=${TICKETOWL_DB_PW}
KEYCLOAK_DB_PASSWORD=${KEYCLOAK_DB_PW}

# Application secrets
NIGHTOWL_SESSION_SECRET=${NIGHTOWL_SESSION_SECRET}
NIGHTOWL_OIDC_CLIENT_SECRET=${NIGHTOWL_OIDC_SECRET}
BOOKOWL_SECRET_KEY=${BOOKOWL_SECRET_KEY}
BOOKOWL_NIGHTOWL_API_KEY=${BOOKOWL_NIGHTOWL_API_KEY}
TICKETOWL_ENCRYPTION_KEY=${TICKETOWL_ENCRYPTION_KEY}
TICKETOWL_NIGHTOWL_API_KEY=${TICKETOWL_NIGHTOWL_API_KEY}
TICKETOWL_BOOKOWL_API_KEY=${TICKETOWL_BOOKOWL_API_KEY}

# Keycloak admin
KEYCLOAK_ADMIN_USER=admin
KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PW}

# MinIO
MINIO_ROOT_USER=${MINIO_ROOT_USER}
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PW}

# URLs
NIGHTOWL_URL=https://nightowl.devops.lab
BOOKOWL_URL=https://bookowl.devops.lab
TICKETOWL_URL=https://ticketowl.devops.lab
KEYCLOAK_URL=https://keycloak.devops.lab
ZAMMAD_URL=https://zammad.devops.lab
CREDS_EOF
chmod 600 "$CREDS_FILE"
echo "    Credentials saved to $CREDS_FILE"

# ---------------------------------------------------------------------------
# Step 4: Print the install command
# ---------------------------------------------------------------------------
echo ""
echo "============================================================================="
echo "  Lab secrets generated successfully!"
echo "============================================================================="
echo ""
echo "To deploy the Owl platform:"
echo ""
echo "  # 1. Build Helm dependencies"
echo "  cd $REPO_DIR"
echo "  helm dep build ."
echo ""
echo "  # 2. Install (or upgrade) the umbrella chart"
echo "  helm install owl . \\"
echo "    --namespace $NAMESPACE \\"
echo "    --create-namespace \\"
echo "    -f values.lab.yaml \\"
echo "    -f values.lab-secrets.yaml"
echo ""
echo "  # Or upgrade an existing release:"
echo "  helm upgrade owl . \\"
echo "    --namespace $NAMESPACE \\"
echo "    -f values.lab.yaml \\"
echo "    -f values.lab-secrets.yaml"
echo ""
echo "  # 3. Keycloak realm is imported automatically via post-install hook."
echo "  #    Check its status with:"
echo "  kubectl get jobs -n $NAMESPACE -l app.kubernetes.io/name=keycloak-realm-import"
echo ""
echo "Credentials file: $CREDS_FILE"
echo "============================================================================="
