{{- if and .Values.externalSecrets.enabled .Values.keep.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keep-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: openbao
    kind: SecretStore
  target:
    name: keep-secrets
    creationPolicy: Owner
    template:
      data:
        DATABASE_CONNECTION_STRING: "{{`{{ .db }}`}}"
        NEXTAUTH_SECRET: "{{`{{ .nextauth }}`}}"
        KEEP_API_KEY: "{{`{{ .apiKey }}`}}"
        OAUTH2_PROXY_CLIENT_SECRET: "{{`{{ .oidcSecret }}`}}"
        OAUTH2_PROXY_COOKIE_SECRET: "{{`{{ .cookieSecret }}`}}"
        KEEP_DEFAULT_API_KEYS: '{{`{{ printf "vector:webhook:%s,nightowl:admin:%s" .apiKey .adminApiKey }}`}}'
  data:
    - secretKey: db
      remoteRef:
        key: platform/owl/keep
        property: database-connection-string
    - secretKey: nextauth
      remoteRef:
        key: platform/owl/keep
        property: nextauth-secret
    - secretKey: apiKey
      remoteRef:
        key: platform/owl/keep
        property: api-key
    - secretKey: adminApiKey
      remoteRef:
        key: platform/owl/keep
        property: admin-api-key
    - secretKey: oidcSecret
      remoteRef:
        key: platform/owl/keep
        property: oidc-client-secret
    - secretKey: cookieSecret
      remoteRef:
        key: platform/owl/keep
        property: cookie-secret
{{- end }}
