{{- if and .Values.externalSecrets.enabled .Values.zammad.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: owl-zammad-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: openbao
    kind: SecretStore
  target:
    name: owl-zammad-secrets
    creationPolicy: Owner
  data:
    - secretKey: postgresql-pass
      remoteRef:
        key: platform/owl/postgresql
        property: zammad-password
    - secretKey: redis-pass
      remoteRef:
        key: platform/owl/redis
        property: password
{{- end }}
