{{- if and .Values.externalSecrets.enabled .Values.postgresql.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: owl-postgresql
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: openbao
    kind: SecretStore
  target:
    name: owl-postgresql
    creationPolicy: Owner
  data:
    - secretKey: postgres-password
      remoteRef:
        key: platform/owl/postgresql
        property: postgres-password
    - secretKey: password
      remoteRef:
        key: platform/owl/postgresql
        property: nightowl-password
    - secretKey: keep-password
      remoteRef:
        key: platform/owl/postgresql
        property: keep-password
    - secretKey: outline-password
      remoteRef:
        key: platform/owl/postgresql
        property: outline-password
    - secretKey: zammad-password
      remoteRef:
        key: platform/owl/postgresql
        property: zammad-password
{{- end }}
