{{- if and .Values.externalSecrets.enabled .Values.outline.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: outline-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: openbao
    kind: SecretStore
  target:
    name: outline-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: platform/owl/outline
        property: database-url
    - secretKey: REDIS_URL
      remoteRef:
        key: platform/owl/outline
        property: redis-url
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: platform/owl/outline
        property: oidc-client-secret
    - secretKey: SECRET_KEY
      remoteRef:
        key: platform/owl/outline
        property: secret-key
    - secretKey: UTILS_SECRET
      remoteRef:
        key: platform/owl/outline
        property: utils-secret
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: platform/owl/outline
        property: aws-access-key-id
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: platform/owl/outline
        property: aws-secret-access-key
{{- end }}
