{{- if and .Values.keycloak.enabled (default true .Values.keycloak.realmImport.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-keycloak-realm-import
  labels:
    {{- include "umbrella-owl.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak-realm-import
type: Opaque
stringData:
  admin-user: {{ required "keycloak.auth.adminUser is required when keycloak.realmImport.enabled=true" .Values.keycloak.auth.adminUser | quote }}
  admin-password: {{ required "keycloak.auth.adminPassword is required when keycloak.realmImport.enabled=true" .Values.keycloak.auth.adminPassword | quote }}
{{- end }}
